networks:
  balance-net:

volumes:
  balance-db-volume:
  balance-backend-volume:

services:
  db:
    image: postgres
    container_name: balance-db
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_USER=balance
      - POSTGRES_PASSWORD=balance
      - POSTGRES_DB=balance
    networks:
      - balance-net
    ports:
      - 5432:5432
    volumes:
      - balance-db-volume:/var/lib/postgresql/data
  backend:
    build: ./balance-backend
    container_name: balance-api
    networks:
      - balance-net
    environment:
      - TZ=Asia/Yangon
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    volumes:
      - balance-backend-volume:/home/spring/slips
    depends_on:
      - db